FROM bpmspace/docker_bpmspace_base:production_server_master
COPY . /var/www/html/
RUN echo chown -R root:root /var/www/html/sqldump/import_sql_all.sh >> /scripts/init.sh
RUN echo chmod +x /var/www/html/sqldump/import_sql_all.sh >> /scripts/init.sh
RUN echo /var/www/html/sqldump/import_sql_all.sh >> /scripts/init.sh
RUN /scripts/init.sh
#ENTRYPOINT /scripts/init.sh