FROM bpmspace/docker_bpmspace_base:production_server_master
COPY . /var/www/html/
RUN ["chmod", "+x", "/var/www/html/sqldump/import_sql_all.sh"]
RUN echo /var/www/html/sqldump/import_sql_all.sh >> /scripts/commands.sh