FROM bpmspace/docker_bpmspace_base:development_server_master
COPY . /var/www/html/liam3
RUN ["chmod", "+x", "/var/www/html/liam3/sqldump/import_sql_all.sh"]
RUN echo chown -R root:root /var/www/html/liam3/sqldump/import_sql_all.sh >> /scripts/commands.sh
RUN echo chmod +x /var/www/html/liam3/sqldump/import_sql_all.sh >> /scripts/commands.sh
RUN echo /var/www/html/liam3/sqldump/liam3/import_sql_all.sh >> /scripts/commands.sh
#ENTRYPOINT /scripts/commands.sh