FROM bpmspace/docker_bpmspace_base:production_server_master
COPY . /var/www/html/
RUN echo touch /tmp/endentrypoint.log >> /usr/local/bin/docker-php-entrypoint
RUN echo chown -R root:root /var/www/html/sqldump/import_sql_all.sh >> /scripts/init.sh
RUN echo chmod +x /var/www/html/sqldump/import_sql_all.sh >> /scripts/init.sh
RUN echo /var/www/html/sqldump/import_sql_all.sh >> /scripts/init.sh
RUN echo /scripts/init.sh >> /usr/local/bin/docker-php-entrypoint